// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_expansions_RCPPEXPORTS_H_GEN_
#define RCPP_expansions_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace expansions {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("expansions", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("expansions", "expansions_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in expansions");
            }
        }
    }

    inline IntegerVector rcpp_intToAry(int n, IntegerVector s) {
        typedef SEXP(*Ptr_rcpp_intToAry)(SEXP,SEXP);
        static Ptr_rcpp_intToAry p_rcpp_intToAry = NULL;
        if (p_rcpp_intToAry == NULL) {
            validateSignature("IntegerVector(*rcpp_intToAry)(int,IntegerVector)");
            p_rcpp_intToAry = (Ptr_rcpp_intToAry)R_GetCCallable("expansions", "expansions_rcpp_intToAry");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rcpp_intToAry(Rcpp::wrap(n), Rcpp::wrap(s));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<IntegerVector >(rcpp_result_gen);
    }

}

#endif // RCPP_expansions_RCPPEXPORTS_H_GEN_
