// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_intToAry
IntegerVector rcpp_intToAry(int n, IntegerVector s);
RcppExport SEXP expansions_rcpp_intToAry(SEXP nSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type s(sSEXP);
    __result = Rcpp::wrap(rcpp_intToAry(n, s));
    return __result;
END_RCPP
}
