// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_intToAry
IntegerVector rcpp_intToAry(int n, IntegerVector s);
RcppExport SEXP expansions_rcpp_intToAry(SEXP nSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_intToAry(n, s));
    return rcpp_result_gen;
END_RCPP
}
