# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_intToAry <- function(n, s) {
    .Call('expansions_rcpp_intToAry', PACKAGE = 'expansions', n, s)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('expansions_RcppExport_registerCCallable', PACKAGE = 'expansions')
})
